[CASETEN]
url=https://www.elc.co.uk/
timeout=10

[PATH]
logger_path=logs
screenshot_path=screenshot
excel_path=testdata/data.xlsx
base_dir = reports
result_directory = reports/allure-results
report_directory = reports/allure-report