[ELC]
url = https://www.elc.co.uk/
timeout = 10

[PATH]
logger_path = logs
screenshot_path = screenshots
excel_path = testdata/data.xlsx

base_dir = reports
allure_results = reports/allure-results
allure_report = reports/allure-report